#pragma once

// Forward Renderer
#define FRAMEBUFFER_FORWARD "Forward_FBO"
#define RENDER_TARGET_FORWARD_COLOR "Forward_Color"
#define RENDER_TARGET_FORWARD_VELOCITY "Forward_Velocity"
#define RENDER_TARGET_FORWARD_DEPTH "Forward_Depth"
#define FRAMEBUFFER_FORWARD_DEPTH_PREPASS "Forward_Depth_Prepass_FBO"
#define RENDER_TARGET_FORWARD_DEPTH_PREPASS "Forward_Depth_Prepass"

// PBR
#define BRDF_LUT "BRDF_LUT"

// CSM
#define CSM_SHADOW_MAPS "CSMShadowMaps"

// Deferred Renderer
#define FRAMEBUFFER_DEFERRED "Deferred_FBO"
#define RENDER_TARGET_DEFERRED_COLOR "Deferred_Color"
#define GBUFFER_FBO "GBuffer_FBO"
#define RENDER_TARGET_GBUFFER_RT0 "GBuffer_RT0"
#define RENDER_TARGET_GBUFFER_RT1 "GBuffer_RT1"
#define RENDER_TARGET_GBUFFER_RT2 "GBuffer_RT2"
#define RENDER_TARGET_GBUFFER_DEPTH "GBuffer_DEPTH"

// Motion Blur
#define FRAMEBUFFER_MOTION_BLUR "Motion_Blur_FBO"
#define RENDER_TARGET_MOTION_BLUR "Motion_Blur_RT"

// SSAO
#define FRAMEBUFFER_SSAO "SSAO_FBO"
#define FRAMEBUFFER_SSAO_BLUR "SSAO_BLUR_FBO"
#define RENDER_TARGET_SSAO "SSAO_RT"
#define RENDER_TARGET_SSAO_BLUR "SSAO_BLUR_RT"

// Tone Mapping
#define RENDER_TARGET_TONE_MAPPING "TONE_MAPPING_RT"
#define FRAMEBUFFER_TONE_MAPPING "TONE_MAPPING_FBO"

// Composition pass
#define SHOW_FORWARD_COLOR 0
#define SHOW_FORWARD_DEPTH 1
#define SHOW_DEFERRED_COLOR 2
#define SHOW_GBUFFER_ALBEDO 3
#define SHOW_GBUFFER_NORMALS 4
#define SHOW_GBUFFER_ROUGHNESS 5
#define SHOW_GBUFFER_METALNESS 6
#define SHOW_GBUFFER_VELOCITY 7
#define SHOW_GBUFFER_EMISSIVE 8
#define SHOW_GBUFFER_DISPLACEMENT 9
#define SHOW_GBUFFER_DEPTH 10
#define SHOW_SHADOW_MAPS 11
#define SHOW_SSAO 20
#define SHOW_SSAO_BLUR 21